name: Custom composite Action
description: Custom action for greet 

inputs:
  name:
    required: true
  language:
    required: false
    default: en

outputs:
  greeted:
    value: true

runs:
  using: "composite"
  steps:
    - name: Greet User
      run: |
        if [ "${{ inputs.language }}" == "en" ]; then
          echo "Hello ${{ inputs.name }}"
        else
          echo "Namaste ${{ inputs.name }}"
        fi
      shell: bash

    - name: Print Info
      run: |
        echo "Date: $(date)"
        echo "OS: $RUNNER_OS"
      shell: bash