name: Environment Variables

on:
    workflow_dispatch:  

env:
    APP_NAME: myapp

jobs:
    env-job:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: staging

        steps:
            - name: Print variables
              env:
                VERSION: 1.0.0 
              run: |
                 echo "App name: $(APP_NAME)"
                 echo "Environment is $(ENVIRONMENT)"
                 echo "Version is $(VERSION)"
                 echo "Commit id :" ${{ github.sha}}
                 echo "Triggered by: " ${{ github.actor}}

