name: First Reusable 

on:
    workflow_call:

        inputs:
            app_name:
                required: true
                type: string 

            environment :
                required: true
                type: string
                default: staging

        secrets:
             docker_token:
                required: true


jobs:
    reusable_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Build app
              run: echo "Building ${{ inputs.app_name }} for ${{inputs.environment }}"

            - name: Check token
              run: |
                if [ -n $"{{secrets.docker_token }}" ]; then
                    echo "Docker token is set: true"
                else
                    echo "Docker token is not set"
                fi 
