name: Scheduled Workflows

on:
    schedule:
        - cron: '30 2 * * 1'
        - cron: '0 */6 * * *'
    workflow_dispatch:
        
jobs:
    health-check-job:
        runs-on: ubuntu-latest
        steps:
            - name: Show triggering Schedule
              run: echo "Triggered by cron schedule ${{ github.event.schedule}}"

            - name: Website Health Check
              run: |
                STATUS=$(curl -o dev/null -s -w "%{http_code}" http://google.com)
                echo "Received Status code : $STATUS"

                if [ "$STATUS" -ne 200 ]; then 
                    echo "Health check failed!"
                    exit 1
                fi
