name: Github Secret

on:
    workflow_dispatch:

jobs:
    secret-demo:
        runs-on: ubuntu-latest
        steps:
            - name: Check secret
              run: | 
                if [ -n "${{secrets.MY_SECRET_MESSAGE}}" ]; then
                    echo "The secret is set: true"
                else
                    echo "The secret is not set: false"
                fi

            - name: Print Secret
              run: echo "$secrets.MY_SECRET_MESSAGE"
