name: self hosted

on: 
    workflow_dispatch:

jobs:
    self-hosted:
        runs-on: my-linux-runner
        steps:
            - name: Checking hostname
              run: echo "Hostname is :" $(hostname)

            - name: Print working directory
              run: echo "Working directory is :" $(pwd)

            - name: Testing files
              run: echo "Hello" > new.txt

