name: Run Tests

on:
        workflow_dispatch:

jobs:
    Running-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Running tests
              run: echo "Running automated tests"